server:
  port: 9000
spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        # 默认数据源
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/dax-pay?serverTimezone=GMT%2B8&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&nullCatalogMeansCurrent=true
          username: root
          password: root
    hikari:
      # 30 秒, 心跳检测
      keepalive-time: 30000
      # 300 分钟, 连接最大存活时间
      max-lifetime: 18000000
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    lettuce:
      cluster:
        refresh:
          # 自适应拓扑刷新
          adaptive: true
          # 群集拓扑刷新周期
          period: 60s
  #静态资源加载配置
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/
  # 定时任务
  quartz:
    # 持久化方式
    job-store-type: jdbc
    #定时任务启动开关，true-开  false-关
    auto-startup: true
    #启动时更新己存在的Job
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzScheduler
            instanceId: AUTO
          threadPool:
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: true
# 项目配置
bootx:
  common:
    # 接口文档
    swagger:
      enabled: false
      author: bootx
      version: 2.0.8
      title: 开源支付平台-单商户
      description: 开源支付平台-单商户版
    # 缓存
    cache:
      # 默认超时时间 30分钟
      default-ttl: 1800
    # 序列生成器
    sequence:
      # 生成方式
      type: jdbc
      # 序列生成器起始值
      range-start: 1
      # 序列生成器区间, 设置1每次都会操作数据库
      range-step: 1
      # 步长
      step: 1
    # 异常
    exception:
      # 显示详细异常
      show-full-message: true
  starter:
    # 认证
    auth:
      # 关闭超级管理员登录
      enable-admin: false
      default-password: 123456
      ignore-urls:
        - '/actuator/**'
        - '/v3/api-docs/**'
        - '/doc.html'
        - '/swagger-resources/**'
        - '/token/**'
        - '/ws/**'
        - '/demo/**'
        - '/test/**'
        - '/webjars/**'
        - '/front/**'
        - '/h5/**'
        - '/css/**'
        - '/error'
        - '/favicon.ico'
    # 审计日志
    audit-log:
      # 审计日志存储
      store: jdbc
      # ip归属地
      ip2region:
        # 数据文件路径, 下载地址 https://gitee.com/lionsoul/ip2region/blob/master/data/ip2region.xdb
        file-path: /data/ip2region/ip2region.xdb
        # 查询方式
        search-type: cache
    # 数据权限
    data-perm:
      #  需要符合AES密钥的要求
      field-decrypt-key: "UCrtxSCwYZNCIlav"
    # 文件上传
    file-upload:
      server-url: http://127.0.0.1:9000
# 自动建表 生产环境关闭
table-modify:
  update-type: none
dromara:
  #文件存储配置,
  x-file-storage:
    #默认使用的存储平台
    default-platform: local
    #缩略图后缀，例如【.min.jpg】【.png】
    thumbnail-suffix: ".min.jpg"
    local-plus:
      # 不启用自带的访问映射, 使用自定义的访问实现
      # 存储平台标识
      - platform: local
        enableStorage: true
        # 文件存储路径
        storage-path: D:/data/files/
# 支付系统配置
dax-pay:
  # 前端h5地址
  front-h5-url: http://pay1.bootx.cn/h5/#
  # 演示模块
  demo:
    # 网关地址
    server-url: http://pay1.bootx.cn/server
    # 前端h5地址
    front-h5-url: http://pay1.bootx.cn/h5/#
    # 签名秘钥
    sign-secret: 123456
    # 签名方式
    sign-type: hmac_sha256
